THREAT_INTEL = {
    "DDoS": {
        "full_name"  : "Distributed Denial of Service",
        "ttps"       : ["T1499 - Endpoint Denial of Service", "T1498 - Network Denial of Service"],
        "description": "Volumetric flood attack overwhelming target with traffic",
        "typical_ports": [80, 443, 53],
        "countermeasures": ["Rate limit inbound SYN", "Null route source IPs", "Enable scrubbing service"],
    },
    "PortScan": {
        "full_name"  : "Port Scanning",
        "ttps"       : ["T1046 - Network Service Discovery"],
        "description": "Attacker probing network for open ports and services",
        "typical_ports": ["any"],
        "countermeasures": ["Block source IP", "Enable port scan detection", "Review firewall rules"],
    },
    "Bot": {
        "full_name"  : "Botnet Activity",
        "ttps"       : ["T1071 - Application Layer Protocol", "T1090 - Proxy"],
        "description": "Compromised host communicating with C2 infrastructure",
        "typical_ports": [80, 443, 6667],
        "countermeasures": ["Quarantine host", "Block C2 domains", "Run malware scan"],
    },
    "FTP-Patator": {
        "full_name"  : "FTP Brute Force",
        "ttps"       : ["T1110 - Brute Force"],
        "description": "Automated credential stuffing attack against FTP service",
        "typical_ports": [21],
        "countermeasures": ["Lock FTP account", "Block source IP", "Enable MFA"],
    },
    "SSH-Patator": {
        "full_name"  : "SSH Brute Force",
        "ttps"       : ["T1110 - Brute Force"],
        "description": "Automated credential stuffing attack against SSH service",
        "typical_ports": [22],
        "countermeasures": ["Lock SSH account", "Block source IP", "Enable key-based auth only"],
    },
    "DoS Hulk": {
        "full_name"  : "DoS Hulk Attack",
        "ttps"       : ["T1499 - Endpoint Denial of Service"],
        "description": "HTTP flood attack generating unique URLs to bypass caching",
        "typical_ports": [80, 443],
        "countermeasures": ["Rate limit HTTP requests", "Enable CAPTCHA", "Block source IPs"],
    },
    "DoS GoldenEye": {
        "full_name"  : "DoS GoldenEye Attack",
        "ttps"       : ["T1499 - Endpoint Denial of Service"],
        "description": "HTTP DoS tool keeping connections alive to exhaust server",
        "typical_ports": [80, 443],
        "countermeasures": ["Limit concurrent connections", "Enable timeout rules"],
    },
    "DoS slowloris": {
        "full_name"  : "Slowloris Attack",
        "ttps"       : ["T1499 - Endpoint Denial of Service"],
        "description": "Slow HTTP attack holding connections open with partial requests",
        "typical_ports": [80, 443],
        "countermeasures": ["Limit connection timeout", "Enable request rate limiting"],
    },
    "DoS Slowhttptest": {
        "full_name"  : "Slow HTTP Test Attack",
        "ttps"       : ["T1499 - Endpoint Denial of Service"],
        "description": "Slow HTTP attack exhausting server connection pool",
        "typical_ports": [80, 443],
        "countermeasures": ["Tune server timeouts", "Enable WAF rules"],
    },
    "Infiltration": {
        "full_name"  : "Network Infiltration",
        "ttps"       : ["T1078 - Valid Accounts", "T1021 - Remote Services"],
        "description": "Attacker has gained internal network access",
        "typical_ports": [445, 3389, 22],
        "countermeasures": ["Isolate affected segment", "Force credential reset", "Enable EDR scan"],
    },
    "Heartbleed": {
        "full_name"  : "Heartbleed OpenSSL Exploit",
        "ttps"       : ["T1212 - Exploitation for Credential Access"],
        "description": "CVE-2014-0160 — memory leak via malformed TLS heartbeat",
        "typical_ports": [443],
        "countermeasures": ["Patch OpenSSL immediately", "Revoke and reissue certificates"],
    },
    "Web Attack Brute Force": {
        "full_name"  : "Web Application Brute Force",
        "ttps"       : ["T1110 - Brute Force"],
        "description": "Automated login attempts against web application",
        "typical_ports": [80, 443],
        "countermeasures": ["Lock account after failed attempts", "Enable CAPTCHA", "Block source IP"],
    },
    "Web Attack XSS": {
        "full_name"  : "Cross-Site Scripting",
        "ttps"       : ["T1059 - Command and Scripting Interpreter"],
        "description": "Malicious scripts injected into web application responses",
        "typical_ports": [80, 443],
        "countermeasures": ["Enable WAF XSS rules", "Sanitize input/output", "Enable CSP headers"],
    },
    "Web Attack Sql Injection": {
        "full_name"  : "SQL Injection",
        "ttps"       : ["T1190 - Exploit Public-Facing Application"],
        "description": "Malicious SQL queries injected to manipulate database",
        "typical_ports": [80, 443],
        "countermeasures": ["Enable WAF SQLi rules", "Use parameterized queries", "Restrict DB permissions"],
    },
    "BENIGN": {
        "full_name"  : "Normal Traffic",
        "ttps"       : [],
        "description": "No threat detected",
        "typical_ports": [],
        "countermeasures": [],
    },
}
